-- Data/StatPriority.lua
-- GENERATED by tools/fetch_stats.py - do not hand-edit; edit
-- tools/wowhead_stats.json and re-run the script.
--
-- Per-spec stat priorities from the guide site's stat-priority guide page for
-- each spec, one list per hero talent tree. Where the guide site splits the
-- priority by something other than the hero tree - a tank's survivability
-- vs DPS goal, a healer's raid vs Mythic+ content - the list title names
-- both hero trees, so every hero spec is covered explicitly rather than
-- silently dropped. Anything the guide site ranks that is not a character stat
-- (item level, weapon damage) is carried in the list's note instead of
-- being invented into the order. This is the guide site's editorial priority at
-- the time each page was read - it goes stale every patch, and the Codex
-- says so - not a sim of your character. See DESIGN.md's "Stat priority".
-- Generated: 2026-09-03 18:03 UTC

local ADDON, ns = ...
if not ns.GuideStore then return end

-- WARRIOR 71 (arms-warrior)
ns.GuideStore:RegisterStatPriority(71, {
  source = "Stat priority guide, updated 2026/08/12",
  url = "https://www.wowhead.com/guide/classes/warrior/arms/stat-priority-pve-dps",
  patch = "12.1",
  heroSplit = true,
  lists = {
    { title = "Colossus",
      list = { { stat = "primary" }, { stat = "crit" }, { stat = "haste" }, { stat = "mastery" }, { stat = "versatility" } },
    },
    { title = "Slayer",
      list = { { stat = "primary" }, { stat = "crit" }, { stat = "haste" }, { stat = "mastery" }, { stat = "versatility" } },
    },
  },
})

-- WARRIOR 72 (fury-warrior)
ns.GuideStore:RegisterStatPriority(72, {
  source = "Stat priority guide, updated 2026/08/12",
  url = "https://www.wowhead.com/guide/classes/warrior/fury/stat-priority-pve-dps",
  patch = "12.1",
  heroSplit = true,
  lists = {
    { title = "Mountain Thane",
      list = { { stat = "primary" }, { stat = "haste" }, { stat = "mastery" }, { stat = "crit" }, { stat = "versatility" } },
    },
    { title = "Slayer",
      list = { { stat = "primary" }, { stat = "haste" }, { stat = "mastery" }, { stat = "crit" }, { stat = "versatility" } },
    },
  },
})

-- WARRIOR 73 (protection-warrior)
ns.GuideStore:RegisterStatPriority(73, {
  source = "Stat priority guide, updated 2026/08/12",
  url = "https://www.wowhead.com/guide/classes/warrior/protection/stat-priority-pve-tank",
  patch = "12.1",
  heroSplit = false,
  lists = {
    { title = "Colossus / Mountain Thane - Survivability",
      note = "The guide splits Protection Warrior by goal, not hero tree, and gives both goals the same order; Crit may pass Haste if your Crit is unusually low or your Haste unusually high",
      list = { { stat = "primary" }, { stat = "haste" }, { stat = "crit" }, { stat = "versatility" }, { stat = "mastery" } },
    },
    { title = "Colossus / Mountain Thane - DPS",
      list = { { stat = "primary" }, { stat = "haste" }, { stat = "crit" }, { stat = "versatility" }, { stat = "mastery" } },
    },
  },
})

-- PALADIN 65 (holy-paladin)
ns.GuideStore:RegisterStatPriority(65, {
  source = "Stat priority guide, updated 2026/08/12",
  url = "https://www.wowhead.com/guide/classes/paladin/holy/stat-priority-pve-healer",
  patch = "12.1",
  heroSplit = true,
  lists = {
    { title = "Herald of the Sun",
      note = "Haste and Crit are ranked equal; item level beats optimising secondaries until you are near max item level",
      list = { { stat = "primary" }, { stat = "mastery" }, { stat = "haste" }, { stat = "crit" }, { stat = "versatility" } },
    },
    { title = "Lightsmith",
      note = "Haste and Crit are ranked equal",
      list = { { stat = "primary" }, { stat = "mastery" }, { stat = "haste" }, { stat = "crit" }, { stat = "versatility" } },
    },
  },
})

-- PALADIN 66 (protection-paladin)
ns.GuideStore:RegisterStatPriority(66, {
  source = "Stat priority guide, updated 2026/08/12",
  url = "https://www.wowhead.com/guide/classes/paladin/protection/stat-priority-pve-tank",
  patch = "12.1",
  heroSplit = false,
  lists = {
    { title = "Lightsmith / Templar - Survivability",
      note = "The guide splits Protection Paladin by goal, not hero tree; both hero trees share these orders",
      list = { { stat = "primary" }, { stat = "haste" }, { stat = "mastery" }, { stat = "crit" }, { stat = "versatility" } },
    },
    { title = "Lightsmith / Templar - DPS",
      list = { { stat = "primary" }, { stat = "haste" }, { stat = "crit" }, { stat = "mastery" }, { stat = "versatility" } },
    },
  },
})

-- PALADIN 70 (retribution-paladin)
ns.GuideStore:RegisterStatPriority(70, {
  source = "Stat priority guide, updated 2026/08/12",
  url = "https://www.wowhead.com/guide/classes/paladin/retribution/stat-priority-pve-dps",
  patch = "12.1",
  heroSplit = true,
  lists = {
    { title = "Templar",
      list = { { stat = "primary" }, { stat = "mastery" }, { stat = "haste" }, { stat = "crit" }, { stat = "versatility" } },
    },
    { title = "Herald of the Sun",
      list = { { stat = "primary" }, { stat = "mastery" }, { stat = "haste" }, { stat = "crit" }, { stat = "versatility" } },
    },
  },
})

-- HUNTER 253 (beast-mastery-hunter)
ns.GuideStore:RegisterStatPriority(253, {
  source = "Stat priority guide, updated 2026/08/12",
  url = "https://www.wowhead.com/guide/classes/hunter/beast-mastery/stat-priority-pve-dps",
  patch = "12.1",
  heroSplit = true,
  lists = {
    { title = "Pack Leader",
      note = "The guide ranks weapon damage ahead of Agility; this order holds in every situation",
      list = { { stat = "primary" }, { stat = "mastery" }, { stat = "crit" }, { stat = "haste" }, { stat = "versatility" } },
    },
    { title = "Dark Ranger",
      note = "Single-target order; in AoE swap to Mastery ahead of Crit, and the gap down to Haste widens. Weapon damage is ranked ahead of Agility",
      list = { { stat = "primary" }, { stat = "crit" }, { stat = "mastery" }, { stat = "haste" }, { stat = "versatility" } },
    },
  },
})

-- HUNTER 254 (marksmanship-hunter)
ns.GuideStore:RegisterStatPriority(254, {
  source = "Stat priority guide, updated 2026/08/12",
  url = "https://www.wowhead.com/guide/classes/hunter/marksmanship/stat-priority-pve-dps",
  patch = "12.1",
  heroSplit = true,
  lists = {
    { title = "Sentinel",
      list = { { stat = "primary" }, { stat = "crit" }, { stat = "mastery" }, { stat = "versatility" }, { stat = "haste" } },
    },
    { title = "Dark Ranger",
      list = { { stat = "primary" }, { stat = "crit" }, { stat = "mastery" }, { stat = "versatility" }, { stat = "haste" } },
    },
  },
})

-- HUNTER 255 (survival-hunter)
ns.GuideStore:RegisterStatPriority(255, {
  source = "Stat priority guide, updated 2026/08/12",
  url = "https://www.wowhead.com/guide/classes/hunter/survival/stat-priority-pve-dps",
  patch = "12.1",
  heroSplit = true,
  lists = {
    { title = "Pack Leader",
      note = "The guide ranks Crit and Haste equal here, with Pack Leader wanting slightly more Haste than Sentinel",
      list = { { stat = "primary" }, { stat = "mastery" }, { stat = "crit" }, { stat = "haste" }, { stat = "versatility" } },
    },
    { title = "Sentinel",
      list = { { stat = "primary" }, { stat = "mastery" }, { stat = "crit" }, { stat = "haste" }, { stat = "versatility" } },
    },
  },
})

-- ROGUE 259 (assassination-rogue)
ns.GuideStore:RegisterStatPriority(259, {
  source = "Stat priority guide, updated 2026/08/12",
  url = "https://www.wowhead.com/guide/classes/rogue/assassination/stat-priority-pve-dps",
  patch = "12.1",
  heroSplit = true,
  lists = {
    { title = "Fatebound",
      list = { { stat = "primary" }, { stat = "crit" }, { stat = "haste" }, { stat = "mastery" }, { stat = "versatility" } },
    },
    { title = "Deathstalker",
      list = { { stat = "primary" }, { stat = "crit" }, { stat = "haste" }, { stat = "mastery" }, { stat = "versatility" } },
    },
  },
})

-- ROGUE 260 (outlaw-rogue)
ns.GuideStore:RegisterStatPriority(260, {
  source = "Stat priority guide, updated 2026/08/12",
  url = "https://www.wowhead.com/guide/classes/rogue/outlaw/stat-priority-pve-dps",
  patch = "12.1",
  heroSplit = true,
  lists = {
    { title = "Trickster",
      list = { { stat = "primary" }, { stat = "haste" }, { stat = "crit" }, { stat = "versatility" }, { stat = "mastery" } },
    },
    { title = "Fatebound",
      list = { { stat = "primary" }, { stat = "haste" }, { stat = "crit" }, { stat = "versatility" }, { stat = "mastery" } },
    },
  },
})

-- ROGUE 261 (subtlety-rogue)
ns.GuideStore:RegisterStatPriority(261, {
  source = "Stat priority guide, updated 2026/08/19",
  url = "https://www.wowhead.com/guide/classes/rogue/subtlety/stat-priority-pve-dps",
  patch = "12.1",
  heroSplit = true,
  lists = {
    { title = "Deathstalker",
      note = "Haste only to roughly 700 rating; more targets or Mythic+ push more of the budget into Mastery, pure single target wants some Crit",
      list = { { stat = "primary" }, { stat = "mastery" }, { stat = "haste" }, { stat = "versatility" }, { stat = "crit" } },
    },
    { title = "Trickster",
      note = "Haste only to roughly 700 rating",
      list = { { stat = "primary" }, { stat = "mastery" }, { stat = "haste" }, { stat = "versatility" }, { stat = "crit" } },
    },
  },
})

-- PRIEST 256 (discipline-priest)
ns.GuideStore:RegisterStatPriority(256, {
  source = "Stat priority guide, updated 2026/08/12",
  url = "https://www.wowhead.com/guide/classes/priest/discipline/stat-priority-pve-healer",
  patch = "12.1",
  heroSplit = true,
  lists = {
    { title = "Oracle",
      note = "The guide states neither hero tree changes the priority in raid or Mythic+; everything below Haste is close, so favour item level",
      list = { { stat = "primary" }, { stat = "haste" }, { stat = "mastery" }, { stat = "crit" }, { stat = "versatility" } },
    },
    { title = "Voidweaver",
      note = "The guide's raid box lists Haste ahead of Intellect for Voidweaver; its Mythic+ box and its own text put Intellect first, which is the order used here",
      list = { { stat = "primary" }, { stat = "haste" }, { stat = "mastery" }, { stat = "crit" }, { stat = "versatility" } },
    },
  },
})

-- PRIEST 257 (holy-priest)
ns.GuideStore:RegisterStatPriority(257, {
  source = "Stat priority guide, updated 2026/08/12",
  url = "https://www.wowhead.com/guide/classes/priest/holy/stat-priority-pve-healer",
  patch = "12.1",
  heroSplit = true,
  lists = {
    { title = "Archon",
      list = { { stat = "primary" }, { stat = "versatility" }, { stat = "crit" }, { stat = "haste" }, { stat = "mastery" } },
    },
    { title = "Oracle",
      list = { { stat = "primary" }, { stat = "versatility" }, { stat = "crit" }, { stat = "haste" }, { stat = "mastery" } },
    },
  },
})

-- PRIEST 258 (shadow-priest)
ns.GuideStore:RegisterStatPriority(258, {
  source = "Stat priority guide, updated 2026/08/31",
  url = "https://www.wowhead.com/guide/classes/priest/shadow/stat-priority-pve-dps",
  patch = "12.1",
  heroSplit = true,
  lists = {
    { title = "Archon",
      list = { { stat = "primary" }, { stat = "haste" }, { stat = "mastery" }, { stat = "crit" }, { stat = "versatility" } },
    },
    { title = "Voidweaver",
      list = { { stat = "primary" }, { stat = "haste" }, { stat = "mastery" }, { stat = "crit" }, { stat = "versatility" } },
    },
  },
})

-- DEATHKNIGHT 250 (blood-death-knight)
ns.GuideStore:RegisterStatPriority(250, {
  source = "Stat priority guide, updated 2026/08/12",
  url = "https://www.wowhead.com/guide/classes/death-knight/blood/stat-priority-pve-tank",
  patch = "12.1",
  heroSplit = true,
  lists = {
    { title = "San'layn",
      note = "The guide ranks Mastery, Crit and Versatility equal below Haste",
      list = { { stat = "primary" }, { stat = "haste" }, { stat = "mastery" }, { stat = "crit" }, { stat = "versatility" } },
    },
    { title = "Deathbringer",
      note = "The guide ranks Mastery and Versatility equal, with Haste last",
      list = { { stat = "primary" }, { stat = "crit" }, { stat = "mastery" }, { stat = "versatility" }, { stat = "haste" } },
    },
  },
})

-- DEATHKNIGHT 251 (frost-death-knight)
ns.GuideStore:RegisterStatPriority(251, {
  source = "Stat priority guide, updated 2026/08/12",
  url = "https://www.wowhead.com/guide/classes/death-knight/frost/stat-priority-pve-dps",
  patch = "12.1",
  heroSplit = true,
  lists = {
    { title = "Deathbringer",
      list = { { stat = "primary" }, { stat = "crit" }, { stat = "mastery" }, { stat = "haste" }, { stat = "versatility" } },
    },
    { title = "Rider of the Apocalypse",
      list = { { stat = "primary" }, { stat = "crit" }, { stat = "mastery" }, { stat = "haste" }, { stat = "versatility" } },
    },
  },
})

-- DEATHKNIGHT 252 (unholy-death-knight)
ns.GuideStore:RegisterStatPriority(252, {
  source = "Stat priority guide, updated 2026/08/17",
  url = "https://www.wowhead.com/guide/classes/death-knight/unholy/stat-priority-pve-dps",
  patch = "12.1",
  heroSplit = true,
  lists = {
    { title = "San'layn",
      list = { { stat = "primary" }, { stat = "crit" }, { stat = "mastery" }, { stat = "haste" }, { stat = "versatility" } },
    },
    { title = "Rider of the Apocalypse",
      list = { { stat = "primary" }, { stat = "crit" }, { stat = "mastery" }, { stat = "haste" }, { stat = "versatility" } },
    },
  },
})

-- SHAMAN 262 (elemental-shaman)
ns.GuideStore:RegisterStatPriority(262, {
  source = "Stat priority guide, updated 2026/08/12",
  url = "https://www.wowhead.com/guide/classes/shaman/elemental/stat-priority-pve-dps",
  patch = "12.1",
  heroSplit = true,
  lists = {
    { title = "Farseer",
      note = "The guide ranks Mastery to about 1200 rating first and lists Intellect last; Haste and Crit are ranked equal, and Mastery is near-useless past the 100% overload cap (about 86% before embellishments)",
      list = { { stat = "mastery" }, { stat = "haste" }, { stat = "crit" }, { stat = "versatility" }, { stat = "primary" } },
    },
    { title = "Stormbringer",
      note = "The guide ranks Mastery to about 1200 rating first and lists Intellect last; Haste and Crit are ranked equal",
      list = { { stat = "mastery" }, { stat = "haste" }, { stat = "crit" }, { stat = "versatility" }, { stat = "primary" } },
    },
  },
})

-- SHAMAN 263 (enhancement-shaman)
ns.GuideStore:RegisterStatPriority(263, {
  source = "Stat priority guide, updated 2026/08/22",
  url = "https://www.wowhead.com/guide/classes/shaman/enhancement/stat-priority-pve-dps",
  patch = "12.1",
  heroSplit = true,
  lists = {
    { title = "Stormbringer",
      note = "Crit and Mastery are ranked equal; the priority does not change between single and multi-target",
      list = { { stat = "primary" }, { stat = "crit" }, { stat = "mastery" }, { stat = "haste" }, { stat = "versatility" } },
    },
    { title = "Totemic",
      note = "Mastery and Haste are ranked equal",
      list = { { stat = "primary" }, { stat = "mastery" }, { stat = "haste" }, { stat = "crit" }, { stat = "versatility" } },
    },
  },
})

-- SHAMAN 264 (restoration-shaman)
ns.GuideStore:RegisterStatPriority(264, {
  source = "Stat priority guide, updated 2026/08/12",
  url = "https://www.wowhead.com/guide/classes/shaman/restoration/stat-priority-pve-healer",
  patch = "12.1",
  heroSplit = true,
  lists = {
    { title = "Farseer",
      note = "The guide gives both hero trees the same order; Haste and Versatility are of similar value and Mastery is a distant last this season",
      list = { { stat = "primary" }, { stat = "crit" }, { stat = "haste" }, { stat = "versatility" }, { stat = "mastery" } },
    },
    { title = "Totemic",
      note = "Haste and Versatility are of similar value; Mastery is a distant last this season",
      list = { { stat = "primary" }, { stat = "crit" }, { stat = "haste" }, { stat = "versatility" }, { stat = "mastery" } },
    },
  },
})

-- MAGE 62 (arcane-mage)
ns.GuideStore:RegisterStatPriority(62, {
  source = "Stat priority guide, updated 2026/08/12",
  url = "https://www.wowhead.com/guide/classes/mage/arcane/stat-priority-pve-dps",
  patch = "12.1",
  heroSplit = true,
  lists = {
    { title = "Spellslinger",
      list = { { stat = "primary" }, { stat = "haste" }, { stat = "mastery" }, { stat = "crit" }, { stat = "versatility" } },
    },
    { title = "Sunfury",
      list = { { stat = "primary" }, { stat = "haste" }, { stat = "versatility" }, { stat = "crit" }, { stat = "mastery" } },
    },
  },
})

-- MAGE 63 (fire-mage)
ns.GuideStore:RegisterStatPriority(63, {
  source = "Stat priority guide, updated 2026/08/12",
  url = "https://www.wowhead.com/guide/classes/mage/fire/stat-priority-pve-dps",
  patch = "12.1",
  heroSplit = true,
  lists = {
    { title = "Sunfury",
      list = { { stat = "primary" }, { stat = "haste" }, { stat = "mastery" }, { stat = "versatility" }, { stat = "crit" } },
    },
    { title = "Frostfire",
      list = { { stat = "primary" }, { stat = "haste" }, { stat = "mastery" }, { stat = "versatility" }, { stat = "crit" } },
    },
  },
})

-- MAGE 64 (frost-mage)
ns.GuideStore:RegisterStatPriority(64, {
  source = "Stat priority guide, updated 2026/08/12",
  url = "https://www.wowhead.com/guide/classes/mage/frost/stat-priority-pve-dps",
  patch = "12.1",
  heroSplit = true,
  lists = {
    { title = "Frostfire",
      list = { { stat = "primary" }, { stat = "mastery" }, { stat = "crit" }, { stat = "haste" }, { stat = "versatility" } },
    },
    { title = "Spellslinger",
      list = { { stat = "primary" }, { stat = "mastery" }, { stat = "crit" }, { stat = "haste" }, { stat = "versatility" } },
    },
  },
})

-- WARLOCK 265 (affliction-warlock)
ns.GuideStore:RegisterStatPriority(265, {
  source = "Stat priority guide, updated 2026/08/12",
  url = "https://www.wowhead.com/guide/classes/warlock/affliction/stat-priority-pve-dps",
  patch = "12.1",
  heroSplit = true,
  lists = {
    { title = "Hellcaller",
      list = { { stat = "primary" }, { stat = "haste" }, { stat = "crit" }, { stat = "versatility" }, { stat = "mastery" } },
    },
    { title = "Soul Harvester",
      list = { { stat = "primary" }, { stat = "haste" }, { stat = "crit" }, { stat = "versatility" }, { stat = "mastery" } },
    },
  },
})

-- WARLOCK 266 (demonology-warlock)
ns.GuideStore:RegisterStatPriority(266, {
  source = "Stat priority guide, updated 2026/08/12",
  url = "https://www.wowhead.com/guide/classes/warlock/demonology/stat-priority-pve-dps",
  patch = "12.1",
  heroSplit = true,
  lists = {
    { title = "Diabolist",
      note = "Haste and Crit are ranked equal, and all stats are close enough that item level is effectively the best stat",
      list = { { stat = "primary" }, { stat = "haste" }, { stat = "crit" }, { stat = "mastery" }, { stat = "versatility" } },
    },
    { title = "Soul Harvester",
      note = "Haste and Crit are ranked equal",
      list = { { stat = "primary" }, { stat = "haste" }, { stat = "crit" }, { stat = "mastery" }, { stat = "versatility" } },
    },
  },
})

-- WARLOCK 267 (destruction-warlock)
ns.GuideStore:RegisterStatPriority(267, {
  source = "Stat priority guide, updated 2026/08/12",
  url = "https://www.wowhead.com/guide/classes/warlock/destruction/stat-priority-pve-dps",
  patch = "12.1",
  heroSplit = true,
  lists = {
    { title = "Diabolist",
      note = "Mastery is ranked at or above Crit, and all stats are close enough that item level is effectively the best stat",
      list = { { stat = "primary" }, { stat = "haste" }, { stat = "mastery" }, { stat = "crit" }, { stat = "versatility" } },
    },
    { title = "Hellcaller",
      note = "Mastery is ranked at or above Crit",
      list = { { stat = "primary" }, { stat = "haste" }, { stat = "mastery" }, { stat = "crit" }, { stat = "versatility" } },
    },
  },
})

-- MONK 268 (brewmaster-monk)
ns.GuideStore:RegisterStatPriority(268, {
  source = "Stat priority guide, updated 2026/08/12",
  url = "https://www.wowhead.com/guide/classes/monk/brewmaster/stat-priority-pve-tank",
  patch = "12.1",
  heroSplit = false,
  lists = {
    { title = "Shado-pan / Master of Harmony - Defensive",
      note = "The guide splits Brewmaster by goal and states both hero trees share these orders; item level, Agility, Armor and Stamina are ranked together first, then Versatility, Crit and Mastery equal, then Haste",
      list = { { stat = "primary" }, { stat = "armor" }, { stat = "stamina" }, { stat = "versatility" }, { stat = "crit" }, { stat = "mastery" }, { stat = "haste" } },
    },
    { title = "Shado-pan / Master of Harmony - Offensive",
      note = "Item level and Agility first, then Crit, then Versatility and Mastery equal, then Haste",
      list = { { stat = "primary" }, { stat = "crit" }, { stat = "versatility" }, { stat = "mastery" }, { stat = "haste" } },
    },
  },
})

-- MONK 270 (mistweaver-monk)
ns.GuideStore:RegisterStatPriority(270, {
  source = "Stat priority guide, updated 2026/08/12",
  url = "https://www.wowhead.com/guide/classes/monk/mistweaver/stat-priority-pve-healer",
  patch = "12.1",
  heroSplit = false,
  lists = {
    { title = "Conduit of the Celestials / Master of Harmony - Raid",
      note = "The guide splits Mistweaver by the celestial the build centres on and the content each is run in, not by hero tree; Haste is first in all content",
      list = { { stat = "primary" }, { stat = "haste" }, { stat = "crit" }, { stat = "versatility" }, { stat = "mastery" } },
    },
    { title = "Conduit of the Celestials / Master of Harmony - Mythic+",
      note = "Mastery moves ahead in Mythic+ for Yu'lon-centred builds",
      list = { { stat = "primary" }, { stat = "haste" }, { stat = "mastery" }, { stat = "crit" }, { stat = "versatility" } },
    },
  },
})

-- MONK 269 (windwalker-monk)
ns.GuideStore:RegisterStatPriority(269, {
  source = "Stat priority guide, updated 2026/08/12",
  url = "https://www.wowhead.com/guide/classes/monk/windwalker/stat-priority-pve-dps",
  patch = "12.1",
  heroSplit = true,
  lists = {
    { title = "Shado-pan",
      list = { { stat = "primary" }, { stat = "haste" }, { stat = "crit" }, { stat = "mastery" }, { stat = "versatility" } },
    },
    { title = "Conduit of the Celestials",
      list = { { stat = "primary" }, { stat = "haste" }, { stat = "mastery" }, { stat = "crit" }, { stat = "versatility" } },
    },
  },
})

-- DRUID 102 (balance-druid)
ns.GuideStore:RegisterStatPriority(102, {
  source = "Stat priority guide, updated 2026/08/12",
  url = "https://www.wowhead.com/guide/classes/druid/balance/stat-priority-pve-dps",
  patch = "12.1",
  heroSplit = true,
  lists = {
    { title = "Keeper of the Grove",
      note = "Haste and Crit are ranked equal",
      list = { { stat = "primary" }, { stat = "mastery" }, { stat = "haste" }, { stat = "crit" }, { stat = "versatility" } },
    },
    { title = "Elune's Chosen",
      list = { { stat = "primary" }, { stat = "mastery" }, { stat = "haste" }, { stat = "crit" }, { stat = "versatility" } },
    },
  },
})

-- DRUID 103 (feral-druid)
ns.GuideStore:RegisterStatPriority(103, {
  source = "Stat priority guide, updated 2026/08/12",
  url = "https://www.wowhead.com/guide/classes/druid/feral/stat-priority-pve-dps",
  patch = "12.1",
  heroSplit = true,
  lists = {
    { title = "Druid of the Claw",
      list = { { stat = "primary" }, { stat = "mastery" }, { stat = "haste" }, { stat = "crit" }, { stat = "versatility" } },
    },
    { title = "Wildstalker",
      list = { { stat = "primary" }, { stat = "mastery" }, { stat = "crit" }, { stat = "haste" }, { stat = "versatility" } },
    },
  },
})

-- DRUID 104 (guardian-druid)
ns.GuideStore:RegisterStatPriority(104, {
  source = "Stat priority guide, updated 2026/08/12",
  url = "https://www.wowhead.com/guide/classes/druid/guardian/stat-priority-pve-tank",
  patch = "12.1",
  heroSplit = false,
  lists = {
    { title = "Druid of the Claw / Elune's Chosen - Survivability",
      note = "The guide splits Guardian by goal, not hero tree, and gives both goals the same order; all four secondaries are close offensively",
      list = { { stat = "primary" }, { stat = "haste" }, { stat = "versatility" }, { stat = "crit" }, { stat = "mastery" } },
    },
    { title = "Druid of the Claw / Elune's Chosen - DPS",
      list = { { stat = "primary" }, { stat = "haste" }, { stat = "versatility" }, { stat = "crit" }, { stat = "mastery" } },
    },
  },
})

-- DRUID 105 (restoration-druid)
ns.GuideStore:RegisterStatPriority(105, {
  source = "Stat priority guide, updated 2026/08/12",
  url = "https://www.wowhead.com/guide/classes/druid/restoration/stat-priority-pve-healer",
  patch = "12.1",
  heroSplit = true,
  lists = {
    { title = "Keeper of the Grove",
      list = { { stat = "primary" }, { stat = "haste" }, { stat = "mastery" }, { stat = "versatility" }, { stat = "crit" } },
    },
    { title = "Wildstalker",
      list = { { stat = "primary" }, { stat = "haste" }, { stat = "mastery" }, { stat = "versatility" }, { stat = "crit" } },
    },
  },
})

-- DEMONHUNTER 577 (havoc-demon-hunter)
ns.GuideStore:RegisterStatPriority(577, {
  source = "Stat priority guide, updated 2026/08/12",
  url = "https://www.wowhead.com/guide/classes/demon-hunter/havoc/stat-priority-pve-dps",
  patch = "12.1",
  heroSplit = true,
  lists = {
    { title = "Fel-Scarred",
      list = { { stat = "primary" }, { stat = "crit" }, { stat = "mastery" }, { stat = "haste" }, { stat = "versatility" } },
    },
    { title = "Aldrachi Reaver",
      list = { { stat = "primary" }, { stat = "crit" }, { stat = "mastery" }, { stat = "haste" }, { stat = "versatility" } },
    },
  },
})

-- DEMONHUNTER 581 (vengeance-demon-hunter)
ns.GuideStore:RegisterStatPriority(581, {
  source = "Stat priority guide, updated 2026/08/25",
  url = "https://www.wowhead.com/guide/classes/demon-hunter/vengeance/stat-priority-pve-tank",
  patch = "12.1",
  heroSplit = true,
  lists = {
    { title = "Aldrachi Reaver",
      note = "Item level is ranked first with Agility and Stamina; below Haste all secondaries are close to equal. Offensively the guide expects Crit, Versatility, Haste, Mastery",
      list = { { stat = "primary" }, { stat = "stamina" }, { stat = "haste" }, { stat = "crit" }, { stat = "versatility" }, { stat = "mastery" } },
    },
    { title = "Annihilator",
      note = "Item level is ranked first with Agility and Stamina; below Haste all secondaries are close to equal",
      list = { { stat = "primary" }, { stat = "stamina" }, { stat = "haste" }, { stat = "crit" }, { stat = "versatility" }, { stat = "mastery" } },
    },
  },
})

-- DEMONHUNTER 1480 (devourer-demon-hunter)
ns.GuideStore:RegisterStatPriority(1480, {
  source = "Stat priority guide, updated 2026/08/12",
  url = "https://www.wowhead.com/guide/classes/demon-hunter/devourer/stat-priority-pve-dps",
  patch = "12.1",
  heroSplit = true,
  lists = {
    { title = "Annihilator",
      note = "Annihilator wants as much Haste as it can get",
      list = { { stat = "primary" }, { stat = "haste" }, { stat = "mastery" }, { stat = "crit" }, { stat = "versatility" } },
    },
    { title = "Void-Scarred",
      note = "Haste only to roughly 800 rating (about 18-20%) and no further - past that it is the worst stat; Crit and Mastery are close, with more Mastery in Mythic+ and more Crit in raid",
      list = { { stat = "primary" }, { stat = "haste" }, { stat = "crit" }, { stat = "mastery" }, { stat = "versatility" } },
    },
  },
})

-- EVOKER 1467 (devastation-evoker)
ns.GuideStore:RegisterStatPriority(1467, {
  source = "Stat priority guide, updated 2026/08/12",
  url = "https://www.wowhead.com/guide/classes/evoker/devastation/stat-priority-pve-dps",
  patch = "12.1",
  heroSplit = true,
  lists = {
    { title = "Flameshaper",
      list = { { stat = "primary" }, { stat = "crit" }, { stat = "mastery" }, { stat = "haste" }, { stat = "versatility" } },
    },
    { title = "Scalecommander",
      list = { { stat = "primary" }, { stat = "crit" }, { stat = "mastery" }, { stat = "haste" }, { stat = "versatility" } },
    },
  },
})

-- EVOKER 1468 (preservation-evoker)
ns.GuideStore:RegisterStatPriority(1468, {
  source = "Stat priority guide, updated 2026/08/31",
  url = "https://www.wowhead.com/guide/classes/evoker/preservation/stat-priority-pve-healer",
  patch = "12.1",
  heroSplit = false,
  lists = {
    { title = "Flameshaper / Chronowarden - Raid",
      note = "The guide splits Preservation by content, not hero tree; secondaries scale off each other, so avoid hard-stacking one",
      list = { { stat = "primary" }, { stat = "crit" }, { stat = "mastery" }, { stat = "haste" }, { stat = "versatility" } },
    },
    { title = "Flameshaper / Chronowarden - Mythic+",
      list = { { stat = "primary" }, { stat = "crit" }, { stat = "haste" }, { stat = "mastery" }, { stat = "versatility" } },
    },
  },
})

-- EVOKER 1473 (augmentation-evoker)
ns.GuideStore:RegisterStatPriority(1473, {
  source = "Stat priority guide, updated 2026/08/12",
  url = "https://www.wowhead.com/guide/classes/evoker/augmentation/stat-priority-pve-dps",
  patch = "12.1",
  heroSplit = true,
  lists = {
    { title = "Chronowarden",
      list = { { stat = "primary" }, { stat = "mastery" }, { stat = "crit" }, { stat = "haste" }, { stat = "versatility" } },
    },
    { title = "Scalecommander",
      list = { { stat = "primary" }, { stat = "mastery" }, { stat = "crit" }, { stat = "haste" }, { stat = "versatility" } },
    },
  },
})
